### ISSUE TITLE
where is  settings.json?

### ISSUE THREAD

**Issue by anoniswho** [Hiero207/ComfyUI-Hiero-Nodes#1]
Settings file not found. Creating default
Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1876, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hiero-Nodes\__init__.py", line 20, in <module>
    with settings_path.open("w", encoding="utf-8") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pathlib.py", line 1044, in open
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\ComfyUI_windows_portable\\custom_nodes\\ComfyUI-Hiero-Nodes\\settings.json'

Cannot import F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hiero-Nodes module for custom nodes: [Errno 2] No such file or directory: 'F:\\ComfyUI_windows_portable\\custom_nodes\\ComfyUI-Hiero-Nodes\\settings.json'

**Comment by Hiero207** [comment]
Sorry about that. I've figured out the error and just pushed a fix for that. Thank you for bringing it to my attention.

#https://github.com/Hiero207/ComfyUI-Hiero-Nodes/commit/97b76fc740fd2bf79a7cda25a7ff435c0b51343a
